package com.norswap.autumn.errors;

import com.norswap.autumn.source.Source;
import com.norswap.autumn.state.CustomState;

/**
 * Interface to be implemented by changes generated by a {@link CustomState} object.
 */
public interface ErrorChanges
{
    ////////////////////////////////////////////////////////////////////////////////////////////////

    /**
     * Creates a new error report from these error changes.
     */
    ErrorReport report(Source source);

    ////////////////////////////////////////////////////////////////////////////////////////////////
}
